/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: IM.Other.proto
 *
 */

import Foundation
import SwiftProtobuf


// service id: 0x0007

///  cmd id:  		0x0701
struct IM_Other_IMHeartBeat: SwiftProtobuf.Message, SwiftProtobuf.Proto2Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf.ProtoNameProviding {
  public var swiftClassName: String {return "IM_Other_IMHeartBeat"}
  public var protoMessageName: String {return "IMHeartBeat"}
  public var protoPackageName: String {return "IM.Other"}
  public static let _protobuf_fieldNames = FieldNameMap()

  public var unknown = SwiftProtobuf.UnknownStorage()

  init() {}

  public mutating func _protoc_generated_decodeField(setter: inout SwiftProtobuf.FieldDecoder, protoFieldNumber: Int) throws {
  }

  public func _protoc_generated_traverse(visitor: inout SwiftProtobuf.Visitor) throws {
    unknown.traverse(visitor: &visitor)
  }

  public func _protoc_generated_isEqualTo(other: IM_Other_IMHeartBeat) -> Bool {
    if unknown != other.unknown {return false}
    return true
  }
}
